### NumPy's dot function

We may sometimes see NumPy's ``dot function`` in places where we would expect a matmul. It turns out that the results of dot and matmul are the same if the matrices are two dimensional.
So these two results are equivalent:

In [2]:
import numpy as np

a = np.array([[1,2],[3,4]])
print("a= \n", a)

print("\n  np.dot(a,a) = \n\n", np.dot(a,a))

print("\n a.dot(a) \n\n", a.dot(a))

print("\n np.matmul(a,a) \n\n", np.matmul(a,a))

a= 
 [[1 2]
 [3 4]]

  np.dot(a,a) = 

 [[ 7 10]
 [15 22]]

 a.dot(a) 

 [[ 7 10]
 [15 22]]

 np.matmul(a,a) 

 [[ 7 10]
 [15 22]]


In [2]:
d=np.array([[[1,2],[3,4]]])
print("\n d= \n", d)
print("\n d.shape =", d.shape)
print("\n   np.dot(d,d) =\n\n", np.dot(d,d))
print("\n  a.dot(d) =  \n\n", a.dot(d))

print("\n np.matmul(d,d) = \n\n", np.matmul(d,d))


 d= 
 [[[1 2]
  [3 4]]]

 d.shape = (1, 2, 2)

   np.dot(d,d) =

 [[[[ 7 10]]

  [[15 22]]]]

  a.dot(d) =  

 [[[ 7 10]]

 [[15 22]]]

 np.matmul(d,d) = 

 [[[ 7 10]
  [15 22]]]


In [3]:
a.dot(d)

array([[[ 7, 10]],

       [[15, 22]]])

In [6]:
np.dot(a,d)

array([[[ 7, 10]],

       [[15, 22]]])

In [7]:
np.dot(d,d)

array([[[[ 7, 10]],

        [[15, 22]]]])

In [8]:
np.dot(d,d)

array([[[[ 7, 10]],

        [[15, 22]]]])

In [9]:
np.matmul(d,d)

array([[[ 7, 10],
        [15, 22]]])

In [10]:
np.matmul(d,d).shape

(1, 2, 2)

In [11]:
d@d

array([[[ 7, 10],
        [15, 22]]])

In [12]:
a=np.random.rand(2,3,3)
print("a = \n" , a)
b=np.random.rand(2,3,3)
print("\n b = \n" , b)

c=a@b

print("\n c = a @ b \n\n", c)

print("\n d=np.dot(a,b) =\n\n",np.dot(a,b))

a = 
 [[[0.05723024 0.93007251 0.75206994]
  [0.09078144 0.51145001 0.55176224]
  [0.68963654 0.28518612 0.23887666]]

 [[0.31730413 0.96370848 0.31644707]
  [0.04340274 0.3050452  0.87502897]
  [0.35116404 0.61748821 0.2907356 ]]]

 b = 
 [[[0.70612601 0.3667213  0.9208861 ]
  [0.68248757 0.34068485 0.22723639]
  [0.87132235 0.08524832 0.00215786]]

 [[0.14742807 0.63960891 0.60282894]
  [0.75567582 0.9666923  0.11081406]
  [0.60368223 0.2715847  0.88606244]]]

 c = a @ b 

 [[[1.33047004 0.40196187 0.26567172]
  [0.89392419 0.25457157 0.20101004]
  [0.88974485 0.37042683 0.70039683]]

 [[0.9660642  1.22050229 0.57846443]
  [0.76515351 0.56029011 0.83529804]
  [0.69390427 0.90048809 0.53772812]]]

 d=np.dot(a,b) =

 [[[[1.33047004 0.40196187 0.26567172]
   [1.16528191 1.1399496  0.80394609]]

  [[0.89392419 0.25457157 0.20101004]
   [0.7329632  0.70232959 0.60029734]]

  [[0.88974485 0.37042683 0.70039683]
   [0.46138564 0.78166015 0.65899513]]]


 [[[1.15750316 0.47165965 0.51187345]

In [13]:
print("c = \n", c , "\n\n c.shape = ",c.shape)

c = 
 [[[1.33047004 0.40196187 0.26567172]
  [0.89392419 0.25457157 0.20101004]
  [0.88974485 0.37042683 0.70039683]]

 [[0.9660642  1.22050229 0.57846443]
  [0.76515351 0.56029011 0.83529804]
  [0.69390427 0.90048809 0.53772812]]] 

 c.shape =  (2, 3, 3)


In [14]:
print("\n d= \n",d , "\n\n d.shape = ", d.shape)


 d= 
 [[[1 2]
  [3 4]]] 

 d.shape =  (1, 2, 2)


In [15]:
print("np.multiply(a,a) = \n\n", np.multiply(a,a) )
print("\n\n np.multiply(a,a).shape = \n\n", np.multiply(a,a).shape )

np.multiply(a,a) = 

 [[[0.0032753  0.86503488 0.56560919]
  [0.00824127 0.26158112 0.30444157]
  [0.47559856 0.08133112 0.05706206]]

 [[0.10068191 0.92873403 0.10013875]
  [0.0018838  0.09305257 0.7656757 ]
  [0.12331618 0.38129169 0.08452719]]]


 np.multiply(a,a).shape = 

 (2, 3, 3)


In [23]:
a=np.array([ [[1,2],[1,2]], [[1,3],[1,3]], [[1,4],[1,4]]
    
])
print("a = \n",a )

print("\n a@a = \n\n", a@a)
print("\n np.dot(a,a) = \n\n", np.dot(a,a))

a = 
 [[[1 2]
  [1 2]]

 [[1 3]
  [1 3]]

 [[1 4]
  [1 4]]]

 a@a = 

 [[[ 3  6]
  [ 3  6]]

 [[ 4 12]
  [ 4 12]]

 [[ 5 20]
  [ 5 20]]]

 np.dot(a,a) = 

 [[[[ 3  6]
   [ 3  9]
   [ 3 12]]

  [[ 3  6]
   [ 3  9]
   [ 3 12]]]


 [[[ 4  8]
   [ 4 12]
   [ 4 16]]

  [[ 4  8]
   [ 4 12]
   [ 4 16]]]


 [[[ 5 10]
   [ 5 15]
   [ 5 20]]

  [[ 5 10]
   [ 5 15]
   [ 5 20]]]]


In [24]:
a*a

array([[[ 1,  4],
        [ 1,  4]],

       [[ 1,  9],
        [ 1,  9]],

       [[ 1, 16],
        [ 1, 16]]])

In [25]:
np.sum(a*a , axis=1)

array([[ 2,  8],
       [ 2, 18],
       [ 2, 32]])

In [26]:
sum(a*a)

array([[ 3, 29],
       [ 3, 29]])

### Transpose

In [34]:
m=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("m =\n", m)

print("\n m.T = \n\n", m.T)
print("\n m.transpose() = \n\n",m.transpose())

m =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 m.T = 

 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

 m.transpose() = 

 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [39]:
m_t = m.T
m_t[3][1] = 200
print("m = \n", m)
print("\n m.T = \n", m.T)

m = 
 [[  1   2   3   4]
 [  5   6   7 200]
 [  9  10  11  12]]

 m.T = 
 [[  1   5   9]
 [  2   6  10]
 [  3   7  11]
 [  4 200  12]]


### A real use case

In [10]:
inputs=np.array([[-0.27,  0.45,  0.64, 0.31]])
print("inputs = \n ", inputs)

print("\n inputs.shape = ", inputs.shape , "\n")

weights = np.array([[0.02, 0.001 , -0.03 , 0.036], \
                    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])
print("weights = \n",weights)
print("\n weights.shape = ",weights.shape)

inputs = 
  [[-0.27  0.45  0.64  0.31]]

 inputs.shape =  (1, 4) 

weights = 
 [[ 0.02   0.001 -0.03   0.036]
 [ 0.04  -0.003  0.025  0.009]
 [ 0.012 -0.045  0.28  -0.067]]

 weights.shape =  (3, 4)


In [13]:
print(np.matmul(weights , inputs))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 4)

In [18]:
print("np.matmul(inputs , weights.T) = \n", np.matmul(inputs , weights.T))

print("\n np.matmul(inputs , weights.T).shape = ", np.matmul(inputs , weights.T).shape)

np.matmul(inputs , weights.T) = 
 [[-0.01299  0.00664  0.13494]]

 np.matmul(inputs , weights.T).shape =  (1, 3)


In [20]:
print("np.matmul(weights, inputs.T) = \n", np.matmul(weights , inputs.T))

print("\n np.matmul(weights, inputs.T).shape = ", np.matmul(weights, inputs.T).shape)

np.matmul(weights, inputs.T) = 
 [[-0.01299]
 [ 0.00664]
 [ 0.13494]]

 np.matmul(weights, inputs.T).shape =  (3, 1)


### Sorting, Subsetting, Slicing, Splitting and Indexing

In [8]:
import numpy as np
a=np.array([[7,32,1],[55,0,-6],[3,99,2]])
print("a = \n", a ,"\n")
print(np.sort(a))
print("\n",np.sort(a , axis=0))
print("\n",np.sort(a , axis=None))

a = 
 [[ 7 32  1]
 [55  0 -6]
 [ 3 99  2]] 

[[ 1  7 32]
 [-6  0 55]
 [ 2  3 99]]

 [[ 3  0 -6]
 [ 7 32  1]
 [55 99  2]]

 [-6  0  1  2  3  7 32 55 99]


### Subsetting

In [30]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("a = \n", a)
print("\n a[1][3] =",a[1][3])
print("\n a[2][1] =",a[2][1])
print("\n a[0]= ",a[0])
print("\n a[:,2] =",a[:,2])
print("\n a[1,:] = ",a[1,:])
print("\n a[0,:] = ",a[0,:])
print("\n a[2,:] = ",a[2,:])
print("\n a[:,1] = ",a[:,1])
print("\n a[:,0] = ",a[:,0])

a = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 a[1][3] = 8

 a[2][1] = 10

 a[0]=  [1 2 3 4]

 a[:,2] = [ 3  7 11]

 a[1,:] =  [5 6 7 8]

 a[0,:] =  [1 2 3 4]

 a[2,:] =  [ 9 10 11 12]

 a[:,1] =  [ 2  6 10]

 a[:,0] =  [1 5 9]


### Slicing

Similar to subsetting, slicing allows us to extract certain portions of an array. For example

In [36]:
a=np.arange(10)
print(a)
s=slice(0,10,2)
print("\n",a[s])

[0 1 2 3 4 5 6 7 8 9]

 [0 2 4 6 8]


In [40]:
a=np.array([67,68,69,89,642,65,9,10])
print(a)
s=slice(0,650,2)
print("\n",a[s])

[ 67  68  69  89 642  65   9  10]

 [ 67  69 642   9]


In [45]:
a=np.arange(10)
print(a)
s=slice(0,10,2)
print("\n",a[s])

[0 1 2 3 4 5 6 7 8 9]

 [0 2 4 6 8]


In [50]:
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [53]:
print(a[::-2])

[9 7 5 3 1]


In [54]:
print(a[:3:-2])

[9 7 5]


In [59]:
print(a[:3:-2])

[9 7 5]


In [61]:
print(a[a>5])

[6 7 8 9]


In [63]:
print(a[(a>5) & (a==5)])

[]


In [66]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
new_arr1= np.array_split(arr1, 4)
print(new_arr1)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
